from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from app.domain.value_objects.action import Action, HtmlPatch


class Fix(BaseModel):
  """
  A fix proposal for a usability issue.
  Holds the HTML patches generated by the Editor Agent.
  """

  model_config = ConfigDict(frozen=False)

  id: str = Field(default_factory=lambda: str(uuid.uuid4()))
  experiment_id: str
  issue_id: str
  instruction: str  # fix instruction in natural language
  patches: list[HtmlPatch] = Field(default_factory=list)
  status: Literal["ok", "ambiguous", "impossible"] = "ok"
  notes: str = ""
  created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

  def apply_editor_result(
    self,
    *,
    status: Literal["ok", "ambiguous", "impossible"],
    patches: list[HtmlPatch],
    notes: str,
  ) -> None:
    self.status = status
    self.patches = patches
    self.notes = notes


class EvaluationResult(BaseModel):
  """
  Fix evaluation result produced by the Preview Agent.
  Determines whether a usability issue is resolved, primarily based on action changes.
  """

  model_config = ConfigDict(frozen=True)

  id: str = Field(default_factory=lambda: str(uuid.uuid4()))
  fix_id: str
  agent_run_id: str
  step: int
  action_changed: bool
  issue_resolved: bool | None  # None = unknown (unable to determine)
  summary: str  # natural language summary
  before_action: Action
  after_action: Action
  created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
