from __future__ import annotations

from bs4 import BeautifulSoup

from app.domain.value_objects.action import HtmlPatch
from app.domain.value_objects.enums import PatchAction


def apply_patches(html: str, patches: list[HtmlPatch]) -> str:
  """
  Apply a list of HtmlPatches to an HTML string in order using BeautifulSoup
  and return the modified HTML string.

  Full implementation of the apply_patches() utility from the design doc
  (design/agents/refinement.md).

  Parameters
  ----------
  html:
      Complete HTML string such as EventSnapshot.raw_html
  patches:
      List of HtmlPatch objects generated by the Editor Agent

  Returns
  -------
  str
      HTML string after all patches have been applied
  """
  soup = BeautifulSoup(html, "html.parser")

  for patch in patches:
    el = soup.select_one(patch.selector)
    if el is None:
      continue  # skip if selector not found

    match patch.action:
      case PatchAction.REPLACE_TEXT:
        el.string = patch.value or ""

      case PatchAction.SET_ATTRIBUTE:
        if patch.name:
          el[patch.name] = patch.value or ""

      case PatchAction.REMOVE_ATTRIBUTE:
        if patch.name and patch.name in el.attrs:
          del el[patch.name]

      case PatchAction.ADD_CLASS:
        classes: list[str] = el.get("class", [])  # type: ignore[assignment]
        if patch.value and patch.value not in classes:
          el["class"] = classes + [patch.value]

      case PatchAction.REMOVE_CLASS:
        classes = el.get("class", [])  # type: ignore[assignment]
        el["class"] = [c for c in classes if c != patch.value]

      case PatchAction.INSERT_BEFORE:
        if patch.value:
          new_tag = BeautifulSoup(patch.value, "html.parser")
          el.insert_before(new_tag)

      case PatchAction.INSERT_AFTER:
        if patch.value:
          new_tag = BeautifulSoup(patch.value, "html.parser")
          el.insert_after(new_tag)

      case PatchAction.REPLACE_ELEMENT:
        if patch.value:
          new_tag = BeautifulSoup(patch.value, "html.parser")
          el.replace_with(new_tag)

      case PatchAction.REMOVE_ELEMENT:
        el.decompose()

      case PatchAction.APPEND_CHILD:
        if patch.value:
          child = BeautifulSoup(patch.value, "html.parser")
          el.append(child)

      case PatchAction.INJECT_STYLE:
        if patch.value:
          style_tag = soup.new_tag("style")
          style_tag.string = patch.value
          body = soup.body
          if body is not None:
            body.append(style_tag)
          else:
            soup.append(style_tag)

  return str(soup)
