"""initial

Revision ID: 6cac033df275
Revises:
Create Date: 2026-02-24 17:13:07.329871

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cac033df275"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "experiments",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("name", sa.Text(), nullable=False),
    sa.Column("target_url", sa.Text(), nullable=False),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "idx_experiments_created_at", "experiments", ["created_at"], unique=False
  )
  op.create_index("idx_experiments_status", "experiments", ["status"], unique=False)
  op.create_table(
    "agent_runs",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("experiment_id", sa.UUID(), nullable=False),
    sa.Column("persona_id", sa.UUID(), nullable=False),
    sa.Column(
      "persona_traits", postgresql.JSONB(astext_type=sa.Text()), nullable=False
    ),
    sa.Column("goal", sa.Text(), nullable=False),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column("success", sa.Boolean(), nullable=True),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(
      ["experiment_id"],
      ["experiments.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "idx_agent_runs_experiment_id", "agent_runs", ["experiment_id"], unique=False
  )
  op.create_index("idx_agent_runs_goal", "agent_runs", ["goal"], unique=False)
  op.create_index(
    "idx_agent_runs_persona_traits_gin",
    "agent_runs",
    ["persona_traits"],
    unique=False,
    postgresql_using="gin",
  )
  op.create_index("idx_agent_runs_status", "agent_runs", ["status"], unique=False)
  op.create_table(
    "experiment_goals",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("experiment_id", sa.UUID(), nullable=False),
    sa.Column("goal", sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(
      ["experiment_id"],
      ["experiments.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint(
      "experiment_id", "goal", name="uq_experiment_goals_experiment_goal"
    ),
  )
  op.create_index(
    "idx_experiment_goals_experiment_id",
    "experiment_goals",
    ["experiment_id"],
    unique=False,
  )
  op.create_table(
    "goal_summaries",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("experiment_id", sa.UUID(), nullable=False),
    sa.Column("goal", sa.Text(), nullable=False),
    sa.Column("agent_count", sa.Integer(), nullable=False),
    sa.Column("success_count", sa.Integer(), nullable=False),
    sa.Column("success_rate", sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column("issue_count", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(
      ["experiment_id"],
      ["experiments.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint(
      "experiment_id", "goal", name="uq_goal_summaries_experiment_goal"
    ),
  )
  op.create_index(
    "idx_goal_summaries_experiment_id",
    "goal_summaries",
    ["experiment_id"],
    unique=False,
  )
  op.create_table(
    "trait_configs",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("experiment_id", sa.UUID(), nullable=False),
    sa.Column("name", sa.Text(), nullable=False),
    sa.Column("key", sa.Text(), nullable=False),
    sa.Column("values", postgresql.ARRAY(sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(
      ["experiment_id"],
      ["experiments.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("experiment_id", "key", name="uq_trait_configs_experiment_key"),
  )
  op.create_index(
    "idx_trait_configs_experiment_id", "trait_configs", ["experiment_id"], unique=False
  )
  op.create_table(
    "event_snapshots",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("agent_run_id", sa.UUID(), nullable=False),
    sa.Column("step", sa.Integer(), nullable=False),
    sa.Column(
      "timestamp",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("raw_html", sa.Text(), nullable=False),
    sa.Column("screenshot", sa.Text(), nullable=False),
    sa.Column("tab_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("reasoning", sa.Text(), nullable=False),
    sa.Column("prompt", sa.Text(), nullable=False),
    sa.Column("action", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("action_result", sa.Text(), nullable=False),
    sa.Column(
      "errors", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
    ),
    sa.ForeignKeyConstraint(
      ["agent_run_id"],
      ["agent_runs.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("agent_run_id", "step", name="uq_event_snapshots_run_step"),
  )
  op.create_index(
    "idx_event_snapshots_agent_run_id",
    "event_snapshots",
    ["agent_run_id"],
    unique=False,
  )
  op.create_table(
    "issues",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("experiment_id", sa.UUID(), nullable=False),
    sa.Column("agent_run_id", sa.UUID(), nullable=False),
    sa.Column("step", sa.Integer(), nullable=False),
    sa.Column("goal", sa.Text(), nullable=False),
    sa.Column("type", sa.Text(), nullable=False),
    sa.Column("element", sa.Text(), nullable=False),
    sa.Column("reason", sa.Text(), nullable=False),
    sa.Column("fix", sa.Text(), nullable=False),
    sa.Column(
      "upt_codes", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
    ),
    sa.Column("upt_explanation", sa.Text(), nullable=False),
    sa.Column("severity", sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(
      ["agent_run_id"],
      ["agent_runs.id"],
    ),
    sa.ForeignKeyConstraint(
      ["experiment_id"],
      ["experiments.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index("idx_issues_agent_run_id", "issues", ["agent_run_id"], unique=False)
  op.create_index("idx_issues_experiment_id", "issues", ["experiment_id"], unique=False)
  op.create_index("idx_issues_goal", "issues", ["goal"], unique=False)
  op.create_index("idx_issues_severity", "issues", ["severity"], unique=False)
  op.create_index(
    "idx_issues_upt_codes_gin",
    "issues",
    ["upt_codes"],
    unique=False,
    postgresql_using="gin",
  )
  op.create_table(
    "step_annotations",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("agent_run_id", sa.UUID(), nullable=False),
    sa.Column("step", sa.Integer(), nullable=False),
    sa.Column("tags", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
    sa.ForeignKeyConstraint(
      ["agent_run_id"],
      ["agent_runs.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("agent_run_id", "step", name="uq_step_annotations_run_step"),
  )
  op.create_index(
    "idx_step_annotations_agent_run_id",
    "step_annotations",
    ["agent_run_id"],
    unique=False,
  )
  op.create_table(
    "trait_distributions",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("goal_summary_id", sa.UUID(), nullable=False),
    sa.Column("trait_key", sa.Text(), nullable=False),
    sa.Column("trait_value", sa.Text(), nullable=False),
    sa.Column("agent_count", sa.Integer(), nullable=False),
    sa.Column("success_rate", sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(
      ["goal_summary_id"],
      ["goal_summaries.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint(
      "goal_summary_id",
      "trait_key",
      "trait_value",
      name="uq_trait_distributions_summary_key_value",
    ),
  )
  op.create_index(
    "idx_trait_distributions_summary_id",
    "trait_distributions",
    ["goal_summary_id"],
    unique=False,
  )
  op.create_table(
    "fixes",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("experiment_id", sa.UUID(), nullable=False),
    sa.Column("issue_id", sa.UUID(), nullable=False),
    sa.Column("instruction", sa.Text(), nullable=False),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column("notes", sa.Text(), server_default="", nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.ForeignKeyConstraint(
      ["experiment_id"],
      ["experiments.id"],
    ),
    sa.ForeignKeyConstraint(
      ["issue_id"],
      ["issues.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index("idx_fixes_experiment_id", "fixes", ["experiment_id"], unique=False)
  op.create_index("idx_fixes_issue_id", "fixes", ["issue_id"], unique=False)
  op.create_table(
    "trait_distribution_issues",
    sa.Column("trait_distribution_id", sa.UUID(), nullable=False),
    sa.Column("issue_id", sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(
      ["issue_id"],
      ["issues.id"],
    ),
    sa.ForeignKeyConstraint(
      ["trait_distribution_id"],
      ["trait_distributions.id"],
    ),
    sa.PrimaryKeyConstraint("trait_distribution_id", "issue_id"),
  )
  op.create_table(
    "evaluation_results",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("fix_id", sa.UUID(), nullable=False),
    sa.Column("agent_run_id", sa.UUID(), nullable=False),
    sa.Column("step", sa.Integer(), nullable=False),
    sa.Column("action_changed", sa.Boolean(), nullable=False),
    sa.Column("issue_resolved", sa.Boolean(), nullable=True),
    sa.Column("summary", sa.Text(), nullable=False),
    sa.Column("before_action", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("after_action", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.ForeignKeyConstraint(
      ["agent_run_id"],
      ["agent_runs.id"],
    ),
    sa.ForeignKeyConstraint(
      ["fix_id"],
      ["fixes.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "idx_evaluation_results_agent_run_id",
    "evaluation_results",
    ["agent_run_id"],
    unique=False,
  )
  op.create_index(
    "idx_evaluation_results_fix_id", "evaluation_results", ["fix_id"], unique=False
  )
  op.create_table(
    "html_patches",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("fix_id", sa.UUID(), nullable=False),
    sa.Column("selector", sa.Text(), nullable=False),
    sa.Column("action", sa.Text(), nullable=False),
    sa.Column("value", sa.Text(), nullable=True),
    sa.Column("name", sa.Text(), nullable=True),
    sa.Column("rationale", sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(
      ["fix_id"],
      ["fixes.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index("idx_html_patches_fix_id", "html_patches", ["fix_id"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index("idx_html_patches_fix_id", table_name="html_patches")
  op.drop_table("html_patches")
  op.drop_index("idx_evaluation_results_fix_id", table_name="evaluation_results")
  op.drop_index("idx_evaluation_results_agent_run_id", table_name="evaluation_results")
  op.drop_table("evaluation_results")
  op.drop_table("trait_distribution_issues")
  op.drop_index("idx_fixes_issue_id", table_name="fixes")
  op.drop_index("idx_fixes_experiment_id", table_name="fixes")
  op.drop_table("fixes")
  op.drop_index("idx_trait_distributions_summary_id", table_name="trait_distributions")
  op.drop_table("trait_distributions")
  op.drop_index("idx_step_annotations_agent_run_id", table_name="step_annotations")
  op.drop_table("step_annotations")
  op.drop_index("idx_issues_upt_codes_gin", table_name="issues", postgresql_using="gin")
  op.drop_index("idx_issues_severity", table_name="issues")
  op.drop_index("idx_issues_goal", table_name="issues")
  op.drop_index("idx_issues_experiment_id", table_name="issues")
  op.drop_index("idx_issues_agent_run_id", table_name="issues")
  op.drop_table("issues")
  op.drop_index("idx_event_snapshots_agent_run_id", table_name="event_snapshots")
  op.drop_table("event_snapshots")
  op.drop_index("idx_trait_configs_experiment_id", table_name="trait_configs")
  op.drop_table("trait_configs")
  op.drop_index("idx_goal_summaries_experiment_id", table_name="goal_summaries")
  op.drop_table("goal_summaries")
  op.drop_index("idx_experiment_goals_experiment_id", table_name="experiment_goals")
  op.drop_table("experiment_goals")
  op.drop_index("idx_agent_runs_status", table_name="agent_runs")
  op.drop_index(
    "idx_agent_runs_persona_traits_gin", table_name="agent_runs", postgresql_using="gin"
  )
  op.drop_index("idx_agent_runs_goal", table_name="agent_runs")
  op.drop_index("idx_agent_runs_experiment_id", table_name="agent_runs")
  op.drop_table("agent_runs")
  op.drop_index("idx_experiments_status", table_name="experiments")
  op.drop_index("idx_experiments_created_at", table_name="experiments")
  op.drop_table("experiments")
  # ### end Alembic commands ###
