"""add_cascade

Revision ID: 8bb58ba8ce05
Revises: 6cac033df275
Create Date: 2026-02-24 17:21:51.841971

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bb58ba8ce05"
down_revision: Union[str, Sequence[str], None] = "6cac033df275"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(
    op.f("agent_runs_experiment_id_fkey"), "agent_runs", type_="foreignkey"
  )
  op.create_foreign_key(
    None, "agent_runs", "experiments", ["experiment_id"], ["id"], ondelete="CASCADE"
  )
  op.drop_constraint(
    op.f("evaluation_results_fix_id_fkey"), "evaluation_results", type_="foreignkey"
  )
  op.drop_constraint(
    op.f("evaluation_results_agent_run_id_fkey"),
    "evaluation_results",
    type_="foreignkey",
  )
  op.create_foreign_key(
    None,
    "evaluation_results",
    "agent_runs",
    ["agent_run_id"],
    ["id"],
    ondelete="CASCADE",
  )
  op.create_foreign_key(
    None, "evaluation_results", "fixes", ["fix_id"], ["id"], ondelete="CASCADE"
  )
  op.drop_constraint(
    op.f("event_snapshots_agent_run_id_fkey"), "event_snapshots", type_="foreignkey"
  )
  op.create_foreign_key(
    None, "event_snapshots", "agent_runs", ["agent_run_id"], ["id"], ondelete="CASCADE"
  )
  op.drop_constraint(
    op.f("experiment_goals_experiment_id_fkey"), "experiment_goals", type_="foreignkey"
  )
  op.create_foreign_key(
    None,
    "experiment_goals",
    "experiments",
    ["experiment_id"],
    ["id"],
    ondelete="CASCADE",
  )
  op.drop_constraint(op.f("fixes_experiment_id_fkey"), "fixes", type_="foreignkey")
  op.drop_constraint(op.f("fixes_issue_id_fkey"), "fixes", type_="foreignkey")
  op.create_foreign_key(
    None, "fixes", "experiments", ["experiment_id"], ["id"], ondelete="CASCADE"
  )
  op.create_foreign_key(
    None, "fixes", "issues", ["issue_id"], ["id"], ondelete="CASCADE"
  )
  op.drop_constraint(
    op.f("goal_summaries_experiment_id_fkey"), "goal_summaries", type_="foreignkey"
  )
  op.create_foreign_key(
    None, "goal_summaries", "experiments", ["experiment_id"], ["id"], ondelete="CASCADE"
  )
  op.drop_constraint(
    op.f("html_patches_fix_id_fkey"), "html_patches", type_="foreignkey"
  )
  op.create_foreign_key(
    None, "html_patches", "fixes", ["fix_id"], ["id"], ondelete="CASCADE"
  )
  op.drop_constraint(op.f("issues_agent_run_id_fkey"), "issues", type_="foreignkey")
  op.drop_constraint(op.f("issues_experiment_id_fkey"), "issues", type_="foreignkey")
  op.create_foreign_key(
    None, "issues", "agent_runs", ["agent_run_id"], ["id"], ondelete="CASCADE"
  )
  op.create_foreign_key(
    None, "issues", "experiments", ["experiment_id"], ["id"], ondelete="CASCADE"
  )
  op.drop_constraint(
    op.f("step_annotations_agent_run_id_fkey"), "step_annotations", type_="foreignkey"
  )
  op.create_foreign_key(
    None, "step_annotations", "agent_runs", ["agent_run_id"], ["id"], ondelete="CASCADE"
  )
  op.drop_constraint(
    op.f("trait_configs_experiment_id_fkey"), "trait_configs", type_="foreignkey"
  )
  op.create_foreign_key(
    None, "trait_configs", "experiments", ["experiment_id"], ["id"], ondelete="CASCADE"
  )
  op.drop_constraint(
    op.f("trait_distribution_issues_trait_distribution_id_fkey"),
    "trait_distribution_issues",
    type_="foreignkey",
  )
  op.drop_constraint(
    op.f("trait_distribution_issues_issue_id_fkey"),
    "trait_distribution_issues",
    type_="foreignkey",
  )
  op.create_foreign_key(
    None,
    "trait_distribution_issues",
    "issues",
    ["issue_id"],
    ["id"],
    ondelete="CASCADE",
  )
  op.create_foreign_key(
    None,
    "trait_distribution_issues",
    "trait_distributions",
    ["trait_distribution_id"],
    ["id"],
    ondelete="CASCADE",
  )
  op.drop_constraint(
    op.f("trait_distributions_goal_summary_id_fkey"),
    "trait_distributions",
    type_="foreignkey",
  )
  op.create_foreign_key(
    None,
    "trait_distributions",
    "goal_summaries",
    ["goal_summary_id"],
    ["id"],
    ondelete="CASCADE",
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(None, "trait_distributions", type_="foreignkey")
  op.create_foreign_key(
    op.f("trait_distributions_goal_summary_id_fkey"),
    "trait_distributions",
    "goal_summaries",
    ["goal_summary_id"],
    ["id"],
  )
  op.drop_constraint(None, "trait_distribution_issues", type_="foreignkey")
  op.drop_constraint(None, "trait_distribution_issues", type_="foreignkey")
  op.create_foreign_key(
    op.f("trait_distribution_issues_issue_id_fkey"),
    "trait_distribution_issues",
    "issues",
    ["issue_id"],
    ["id"],
  )
  op.create_foreign_key(
    op.f("trait_distribution_issues_trait_distribution_id_fkey"),
    "trait_distribution_issues",
    "trait_distributions",
    ["trait_distribution_id"],
    ["id"],
  )
  op.drop_constraint(None, "trait_configs", type_="foreignkey")
  op.create_foreign_key(
    op.f("trait_configs_experiment_id_fkey"),
    "trait_configs",
    "experiments",
    ["experiment_id"],
    ["id"],
  )
  op.drop_constraint(None, "step_annotations", type_="foreignkey")
  op.create_foreign_key(
    op.f("step_annotations_agent_run_id_fkey"),
    "step_annotations",
    "agent_runs",
    ["agent_run_id"],
    ["id"],
  )
  op.drop_constraint(None, "issues", type_="foreignkey")
  op.drop_constraint(None, "issues", type_="foreignkey")
  op.create_foreign_key(
    op.f("issues_experiment_id_fkey"),
    "issues",
    "experiments",
    ["experiment_id"],
    ["id"],
  )
  op.create_foreign_key(
    op.f("issues_agent_run_id_fkey"), "issues", "agent_runs", ["agent_run_id"], ["id"]
  )
  op.drop_constraint(None, "html_patches", type_="foreignkey")
  op.create_foreign_key(
    op.f("html_patches_fix_id_fkey"), "html_patches", "fixes", ["fix_id"], ["id"]
  )
  op.drop_constraint(None, "goal_summaries", type_="foreignkey")
  op.create_foreign_key(
    op.f("goal_summaries_experiment_id_fkey"),
    "goal_summaries",
    "experiments",
    ["experiment_id"],
    ["id"],
  )
  op.drop_constraint(None, "fixes", type_="foreignkey")
  op.drop_constraint(None, "fixes", type_="foreignkey")
  op.create_foreign_key(
    op.f("fixes_issue_id_fkey"), "fixes", "issues", ["issue_id"], ["id"]
  )
  op.create_foreign_key(
    op.f("fixes_experiment_id_fkey"), "fixes", "experiments", ["experiment_id"], ["id"]
  )
  op.drop_constraint(None, "experiment_goals", type_="foreignkey")
  op.create_foreign_key(
    op.f("experiment_goals_experiment_id_fkey"),
    "experiment_goals",
    "experiments",
    ["experiment_id"],
    ["id"],
  )
  op.drop_constraint(None, "event_snapshots", type_="foreignkey")
  op.create_foreign_key(
    op.f("event_snapshots_agent_run_id_fkey"),
    "event_snapshots",
    "agent_runs",
    ["agent_run_id"],
    ["id"],
  )
  op.drop_constraint(None, "evaluation_results", type_="foreignkey")
  op.drop_constraint(None, "evaluation_results", type_="foreignkey")
  op.create_foreign_key(
    op.f("evaluation_results_agent_run_id_fkey"),
    "evaluation_results",
    "agent_runs",
    ["agent_run_id"],
    ["id"],
  )
  op.create_foreign_key(
    op.f("evaluation_results_fix_id_fkey"),
    "evaluation_results",
    "fixes",
    ["fix_id"],
    ["id"],
  )
  op.drop_constraint(None, "agent_runs", type_="foreignkey")
  op.create_foreign_key(
    op.f("agent_runs_experiment_id_fkey"),
    "agent_runs",
    "experiments",
    ["experiment_id"],
    ["id"],
  )
  # ### end Alembic commands ###
