from __future__ import annotations

from typing import Literal

from pydantic import BaseModel

from app.domain.value_objects.enums import PatchAction


class TabMetadata(BaseModel):
  """Browser tab metadata."""

  url: str
  title: str


class Action(BaseModel):
  """Browser action performed by the agent."""

  type: Literal["click", "scroll", "type", "navigate"]
  selector: str | None = None
  value: str | None = None

  def __eq__(self, other: object) -> bool:
    if not isinstance(other, Action):
      return False
    return (
      self.type == other.type
      and self.selector == other.selector
      and self.value == other.value
    )


class HtmlPatch(BaseModel):
  """HTML DOM patch generated by the Editor Agent."""

  selector: str
  action: PatchAction
  value: str | None = None
  name: str | None = None  # used by set_attribute / remove_attribute
  rationale: str


class EditorResult(BaseModel):
  """Result of an Editor Agent execution."""

  status: Literal["ok", "ambiguous", "impossible"]
  patches: list[HtmlPatch]
  notes: str
