from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Awaitable, Callable
from dataclasses import dataclass, field

from app.domain.value_objects.persona import Persona


@dataclass
class StepData:
  """
  Raw data for one step of a browser agent.
  This is the format returned by BrowserPort; SimulationAgent converts it
  into an EventSnapshot.
  """

  step: int
  html: str
  screenshot: str  # base64 PNG
  reasoning: str  # think-aloud text
  full_prompt: str  # full prompt sent to the LLM
  action_type: str  # click / scroll / type / navigate
  action_selector: str | None
  action_value: str | None
  action_result: str
  errors: list[str] = field(default_factory=list)
  tab_url: str = ""
  tab_title: str = ""


class BrowserPort(ABC):
  """
  Abstract interface (Port) for browser operations.

  Implementations (Adapters) are provided by frameworks such as browser-use
  and are placed in the Infrastructure layer. This keeps SimulationAgent
  independent of any concrete browser implementation.
  """

  @abstractmethod
  async def run_simulation(
    self,
    url: str,
    task: str,
    behavior_prompt: str,
    max_steps: int,
    on_step: Callable[[StepData], Awaitable[None]],
  ) -> bool:
    """
    Run a simulation against the target URL.

    Parameters
    ----------
    url:
        URL of the website to simulate
    task:
        Task instruction for the agent (TASK_PROMPT)
    behavior_prompt:
        Persona behavior instruction (BEHAVIOR_PROMPT), passed as the system prompt
    max_steps:
        Maximum number of steps to execute
    on_step:
        Async callback invoked on each step completion

    Returns
    -------
    bool
        Whether the goal is considered achieved
    """
    ...

  @abstractmethod
  async def run_single_step_with_html(
    self,
    fixed_html: str,
    prompt_history: list[dict],
    persona: Persona,
    behavior_prompt: str,
  ) -> StepData:
    """
    Re-run one step using a fixed HTML snapshot (for Preview Agent).

    Parameters
    ----------
    fixed_html:
        HTML with patches generated by Editor Agent already applied
    prompt_history:
        Prompt history retrieved from the original simulation
    persona:
        Persona to use for re-simulation
    behavior_prompt:
        Persona behavior instruction (BEHAVIOR_PROMPT)
    """
    ...
